- .github/workflows/pr_script.yml
- README.md
- pr_script.py
Adds  a workflow to run a script against a PR as a maintainer.  The workflow is meant to be run from a fork using the maintainer's own GitHub credentials.
> Add a PR Script Workflow

- .github/workflows/pr_script.yml
- pr_script.py
> Add support for custom commit messages

- .github/actions/enforce-label/action.yml
Give time for maintainer to select a label or for a labeler workflow to run
> Sleep for 60 seconds on PR open in Label Enforcer

- .github/actions/downstream-test/action.yml
- README.md
Fixes #20.
I decided not to use `--pre` since it pulls in prereleases of all packages, not just the one specified.
Tested in https://github.com/jupyter/jupyter_client/pull/725
> Add downstream tester

- .github/actions/binder-link/action.yml
The action would otherwise give the following error:
```
ReferenceError: $CONTENT is not defined
```
> Fix use of `CONTENT` in `binder-link` action

- CHANGELOG.md
Automated Changelog Entry for 0.4.4 on main
| Since | v1 |
> Automated Changelog Entry for 0.4.4 on main

- .github/actions/pr-script/action.yml
- .github/actions/pr-script/pr_script.py
- .github/workflows/pr_script.yml
- README.md
> Add PR script action

- .github/actions/pr-script/action.yml
- .github/actions/pr-script/pr_script.py
- .github/workflows/tests.yml
- README.md
Follow up to #37.
After doing some [testing](https://github.com/blink1073/test-python-project/pull/3), here is what I found out:
- The `GITHUB_TOKEN` provided in the workflow is not tied to the commenter, so 
we should not allow a script to be given directly (could lead to malicious scripts),
and we should limit users by [Author Association](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation).
- As mentioned in the Readme update, the resulting commit will not cause a workflow to trigger, unless
you decide to use a personal access token as the secret.  The risk of doing so is mitigated by 
limiting the script as described in the previous bullet.
- Ideally `jupyterlab-probot` should be augmented to handle this functionality, since it can push
with its own …
> Clean up PR script workflow

- README.md
cc @martinRenou @fcollonval we needed to add `contents: write` permission.  `pull_requests: write` allows you to affect the PR metadata and comments, not the PR content.  This was proven out in https://github.com/jupyter-server/jupyter_server/pull/686
> Clean up usage docs for PR Script

- CHANGELOG.md
Automated Changelog Entry for 0.6.2 on main
| Since | v1 |
> Automated Changelog Entry for 0.6.2 on main

- .github/actions/update-snapshots/action.yml
- .github/workflows/tests.yml
- README.md
Playwright supports starting the server from its `webServer` configuration parameter.
This adapts the update snapshots action to support that case.
> Support starting server from Playwright config

- CHANGELOG.md
Automated Changelog Entry for 0.6.3 on main
| Version Spec | 0.6.3 |
| Since | v0.6.2 |
> Automated Changelog Entry for 0.6.3 on main

- CHANGELOG.md
Automated Changelog Entry for 0.7.0 on main
| Version Spec | minor |
| Since | v1 |
> Automated Changelog Entry for 0.7.0 on main

- CHANGELOG.md
Automated Changelog Entry for 0.8.0 on main
| Version Spec | minor |
| Since | v1 |
> Automated Changelog Entry for 0.8.0 on main

- CHANGELOG.md
Automated Changelog Entry for 0.8.1 on main
| Since | v1 |
> Automated Changelog Entry for 0.8.1 on main

- CHANGELOG.md
Automated Changelog Entry for 0.8.2 on main
| Since | v1 |
> Automated Changelog Entry for 0.8.2 on main

- .github/actions/downstream-test/action.yml
These are not included in the venv by default
> Include wheel and setuptools in downstream test

- CHANGELOG.md
Automated Changelog Entry for 0.8.3 on main
| Since | v1 |
> Automated Changelog Entry for 0.8.3 on main

- CHANGELOG.md
Automated Changelog Entry for 0.8.4 on main
| Since | v1 |
> Automated Changelog Entry for 0.8.4 on main

- .github/actions/base-setup/action.yml
- .github/actions/downstream-test/action.yml
Use pytest args used by ipython CI.
Also install `pytest-github-actions-annotate-failures` in the base setup function
> Clean up default downstream test defaults

- CHANGELOG.md
Automated Changelog Entry for 0.8.5 on main
| Since | v1 |
> Automated Changelog Entry for 0.8.5 on main

- .github/actions/downstream-test/action.yml
> Use a different directory for downstream tests

- CHANGELOG.md
Automated Changelog Entry for 0.8.6 on main
| Since | v1 |
> Automated Changelog Entry for 0.8.6 on main

- CHANGELOG.md
Automated Changelog Entry for 0.10.0 on main
| Version Spec | minor |
| Since | v1 |
> Automated Changelog Entry for 0.10.0 on main

- .github/actions/update-snapshots/action.yml
This is a workaround to get the snapshots even if the fork is in another organization - that forbids pushing new commit to the PR branch.
> Upload snapshots as artifact

- CHANGELOG.md
Automated Changelog Entry for 0.11.0 on main
| Version Spec | minor |
| Since | v1 |
> Automated Changelog Entry for 0.11.0 on main

- .github/actions/enforce-label/action.yml
Debugged with the following code:
```python
from ghapi.all import GhApi
api = GhApi(owner='jupyterlab', repo='jupyterlab')
api.issues.get(12384).user.login
```
> Fix bot user names

- CHANGELOG.md
Automated Changelog Entry for 0.11.1 on main
| Since | v1 |
> Automated Changelog Entry for 0.11.1 on main

- CHANGELOG.md
Automated Changelog Entry for 0.11.2 on main
| Since | v1 |
> Automated Changelog Entry for 0.11.2 on main

- CHANGELOG.md
Automated Changelog Entry for 0.11.3 on main
| Since | v1 |
> Automated Changelog Entry for 0.11.3 on main

- .github/workflows/tests.yml
Bug seen in https://github.com/jupyterlab/maintainer-tools/runs/7664161390?check_suite_focus=true
The getting started page of Playwright.dev changed its title.
> Fix update snapshots tests

- .github/actions/test-sdist/action.yml
Install package in `--editable` mode to ensure test files are present. Solves #113.
> Ensure package is installed with test files in test-sdist

- CHANGELOG.md
Automated Changelog Entry for 0.11.4 on main
| Since | v1 |
> Automated Changelog Entry for 0.11.4 on main

- .github/actions/check-links/action.yml
- .github/actions/check-links/check_links.py
- .github/workflows/check-release.yml
- .github/workflows/tests.yml
- README.md
Move the `check-links` functionality from `jupyter_releaser` here, so we can drop it from `jupyter_releaser@v2`.
> Add check links action

- CHANGELOG.md
Automated Changelog Entry for 0.14.0 on main
| Draft Release | https://github.com/jupyterlab/maintainer-tools/releases/tag/untagged-765a54c7faed972a525d  |
| Since | v1 |
> Automated Changelog Entry for 0.14.0 on main

- .github/actions/install-minimums/action.yml
- .github/actions/install-minimums/create_constraints_file.py
- .github/workflows/tests.yml
- pyproject.toml
Handle complex constraints like `jupyter_core>=4.12,!=~5.0`.  Also drop dependency on `pkginfo`.
> Clean up create constraints

- .github/actions/check-links/check_links.py
- .github/dependabot.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- pyproject.toml
cf https://github.com/jupyter-server/jupyter_server/pull/1114
> Adopt ruff and address lint

- .github/actions/update-snapshots/action.yml
Making integration tests robust for snapshots update can be more challenging as the actions are executed faster than in the test.
This PR makes the action forgiving.
> Don't fail if errors occurred when updating snapshots

- .github/actions/base-setup/action.yml
Related to https://github.com/jupyterlab/jupyterlab/pull/13722 (issue https://github.com/jupyterlab/jupyterlab/issues/13720), updates the default NodeJS version from 16.x to 18.x.
> Updates default minimum node version from 16 to 18

- .github/actions/update-snapshots/action.yml
continue-on-error is not working as I forgot inputs are strings.
See error in that run: https://github.com/jupyterlab/jupyterlab/actions/runs/3940040404/jobs/6740639988
```
Error: jupyterlab/maintainer-tools/v1/.github/actions/update-snapshots/action.yml (Line: 80, Col: 26): Unexpected value 'true'
Error: The step failed and an error occurred when attempting to determine whether to continue on error.
Error: The template is not valid. jupyterlab/maintainer-tools/v1/.github/actions/update-snapshots/action.yml (Line: 80, Col: 26): Unexpected value 'true'
```
> Fix `continue-on-error` configuration

- .github/actions/base-setup/action.yml
Working at updating `jlpm` to yarn3, the base setup is failing because of changes in the CLI command to get the cache directory.
Would it be possible to add a new tagged version including this ?
> Update command to get cache directory with yarn3

- .github/actions/report-coverage/action.yml
- .github/actions/upload-coverage/action.yml
- .github/workflows/tests.yml
- README.md
Based on https://hynek.me/articles/ditch-codecov-python/ and https://about.codecov.io/blog/message-regarding-the-pypi-package/
> Add coverage report handling

- .github/actions/update-snapshots/action.yml
- README.md
Add support for providing a custom yarn command for the `jupyterlab/maintainer-tools/.github/actions/update-snapshots@v1` action.
This is useful to provide a custom yarn version, or `jlpm` which has been updated to yarn 3.
> Add input to configure the yarn command via `npm_client`

- README.md
Port https://github.com/jupyterlab/jupyterlab/pull/15070 to the Galata update example workflow.
> Update example workflow to include comment reaction (:+1:)

- .github/actions/report-coverage/action.yml
The errors are usually spurious.
> Ignore coverage combine errors

- CHANGELOG.md
- package.json
Not sure why but the changelog for `0.25.0` includes more changes than needed.
Maybe it's because I checked this box when doing the release:
> Fix `0.25.0` changelog

- .github/actions/check-links/check_links.py
Addresses recent failures seen across libs for rate limiting https://github.com/ipython/ipykernel/actions/runs/8537763809/job/23389024807?pr=1227
> Skip github usernames in link check

- .github/actions/base-setup/action.yml
- package.json
> Fix handling of dependencies

- .github/actions/base-setup/action.yml
- .github/actions/make-sdist/action.yml
- .github/actions/report-coverage/action.yml
- .github/actions/test-sdist/action.yml
- .github/actions/update-snapshots/action.yml
- .github/actions/upload-coverage/action.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
Upgrade actions to use NodeJS 20 and remove warning about node 16
Fixes https://github.com/jupyterlab/jupyterlab/issues/15698
> Upgrade actions

- .github/actions/base-setup/action.yml
- .github/workflows/tests.yml
- package.json
Fixes #240 
`packageManager` has been added to package.json to test this.
> Enable corepack if `packageManager` is defined

- .github/actions/base-setup/action.yml
> Include (potentially nested) `pyproject.toml` files in the pip hash key

- .github/actions/upload-coverage/action.yml
Looks like we now need to set this option when uploading coverage, since the default file starts with a leading `.` and is likely considered as ignored.
https://github.com/actions/upload-artifact/releases/tag/v4.4.0
This would explain why the coverage check started failing on notebook: https://github.com/jupyter/notebook/issues/7456
> Enable `include-hidden-files` for `actions/upload-artifact@v4`

- .github/actions/report-coverage/action.yml
Follow-up to #245 
Fixes https://github.com/jupyter/notebook/issues/7456
Closes https://github.com/jupyter/notebook/pull/7457
We likely need `include-hidden-files` to be set for `actions/upload-artifact/merge@v4` too.
> Add `include-hidden-files: true` to `report-coverage` action

- .github/actions/binder-link/action.yml
- .github/actions/enforce-label/action.yml
This should help fix some of these warnings, as seen on other repos using the `enforce-label` action:
> Bump to `actions/github-script@v7`

- .github/actions/base-setup/action.yml
- .github/actions/report-coverage/action.yml
- .github/workflows/tests.yml
- README.md
Start testing on Python 3.13. This PR:
- Bumps the default (standard) version to Python 3.12
- Bumps the pre version to Python 3.13
> CI: Bump pre to Python 3.13, standard to 3.12

- .github/actions/base-setup/create_constraints_file.py
- .github/actions/base-setup/setup_constraints.sh
> Support extracting minimum constraints for monorepo

- .github/actions/base-setup/action.yml
out-of-date pipx can cause problems and is never explicitly installed, though it is explicitly required
> make sure pipx is installed, up-to-date
