jupyterlab/maintainer-tools

- .github/actions/enforce-label/action.yml
- .github/workflows/enforce-label.yml
- README.md
> Add label enforcer

- .github/actions/base-setup/action.yml
- .github/workflows/check-release.yml
- README.md
Fixes #4.  Adds common steps used across various Jupyter repos
> Add base setup action

- README.md
Addresses https://github.com/jupyter-server/jupyter_releaser/issues/204
> Add docs about the triage labels

- .github/workflows/pr_script.yml
So it's a bit more specific than the current `build`:
> Update PR script job name to `run`

- .github/actions/downstream-test/action.yml
Needed to support https://github.com/jupyter-server/jupyter_server/pull/629
> Make the downstream tester more configurable

- .github/actions/binder-link/action.yml
Update the text since folks that be launching something else than a notebook on Binder.
> Update body text for the Binder link comment

- .github/workflows/pr_script.yml
> Fix handling of github token in action workflow

- .github/actions/update-snapshots/action.yml
Error seen in https://github.com/jupyterlab/jupyterlab/runs/5334866554?check_suite_focus=true
> Support git repository not in worflow root

- .github/actions/base-setup/action.yml
- .github/workflows/tests.yml
- README.md
> Add version inputs to base setup action

- .github/actions/enforce-label/action.yml
- .github/workflows/enforce-label.yml
> Use custom script for enforce label

- .github/actions/downstream-test/action.yml
> Clean up handling of downstream tests

- .github/actions/downstream-test/action.yml
> Fix cleanup of downstream test venv

- README.md
> Update docs on test-sdist

- .github/actions/update-snapshots/action.yml
Address error seen in https://github.com/jupyterlab/jupyterlab/runs/5828286417
> Fix push error

- .github/actions/enforce-label/action.yml
- README.md
> Automatically add maintainence label for known bots

- .github/actions/base-setup/action.yml
- .github/actions/downstream-test/action.yml
- .github/actions/install-minimums/action.yml
- .github/actions/test-sdist/action.yml
- .github/workflows/pr_script.yml
> Clean up log output and use boolean input value in pr_script workflow

- .github/actions/test-sdist/action.yml
> Fix default test command in test-sdist

- .github/actions/base-setup/action.yml
- .github/workflows/tests.yml
Addresses error seen in [jupyterlab build](https://github.com/jupyterlab/jupyterlab/runs/6540657069?check_suite_focus=true).
"ERROR: To modify pip, please run the following command:
C:\hostedtoolcache\windows\Python\3.9.12\x64\python.exe -m pip install --upgrade pip setuptools wheel pytest-github-actions-annotate-failures --user"
> Update workflows and base setup

- .github/actions/base-setup/action.yml
Upgraded default Python to 3.10, and Node to 16.x, the current LTS version.
> Upgraded python and node versions

- .github/actions/install-minimums/action.yml
- .github/actions/install-minimums/create_constraints_file.py
- .github/workflows/tests.yml
- README.md
Enables using minimum versions in a virtual env such as ``hatch``
> Add ability to only create constraints file

- .github/actions/check-links/check_links.py
> Log the output when a link check fails

- .github/actions/check-links/check_links.py
Follow-up to https://github.com/jupyterlab/maintainer-tools/pull/161
> Decode check links output on failure

- .github/actions/base-setup/action.yml
This PR fixes https://github.com/jupyterlab/maintainer-tools/pull/179
> Yarn cache dir action working for every version of yarn

- .github/actions/base-setup/action.yml
cf https://github.com/pypa/pip/issues/12053
> Allow pip list to fail

- .github/actions/base-setup/action.yml
cf https://github.com/pypa/pip/issues/12053
> Allow pip debug to fail

- .github/actions/base-setup/action.yml
Addresses https://github.com/jupyter-server/jupyter_releaser/actions/runs/7228495000/job/19698030252
> Install hatch with global python

- .github/actions/base-setup/action.yml
Update the default Node.js version to the latest stable LTS.
> Bump to Node.js 20 by default

- .github/actions/base-setup/action.yml
- README.md
- package.json
> Do not try and handle deps on Windows

- .github/actions/base-setup/action.yml
- .github/actions/base-setup/create_constraints_file.py
- .github/actions/base-setup/setup_constraints.sh
- .github/actions/downstream-test/action.yml
> Do not use constraints file for downstream test

- .github/actions/base-setup/action.yml
https://github.com/pypa/hatch/tree/install
> Use hatch install action

- .github/actions/binder-link/action.yml
> Encode branch name
